# This docker-compose file will assume that docker swarm is enabled. One node swarm cluster is sufficient to test this.
# 1. First build the images with "docker-compose -f docker-compose-v2.yml build --no-cache".
# 2. Then Run "docker swarm init" to initialize a single node swarm cluster.
# 3. Next run "./create-docker-secret.sh" to create docker secrets to be used with the containers.
# 4. Finally run "docker stack deploy --compose-file docker-compose-v2.yml".
# 5. Verify if services are running healthily.
version: "3.9"
services:
  app-receiver:
    # SOME
    # PARAMETERS
    # ARE MISSING
    image: app-receiver:latest
    # SOME
    # PARAMETERS
    # ARE MISSING
  app-sender:
    # SOME
    # PARAMETERS
    # ARE MISSING
    image: app-sender:latest
    # SOME
    # PARAMETERS
    # ARE MISSING
    # SOME
    # PARAMETERS
    # ARE MISSING
secrets:
# SOME
# PARAMETERS
# ARE MISSING