FROM python:3 as production_image

ENV SCAN_INTERVAL="1"
ENV INPUT_DIR="/usr/src/app-sender/input"
ENV ENCRYPTION_KEY="/run/secrets/encryption_key"
ENV STATUS_DB_PATH="/usr/src/app-sender/status-db"
ENV RECEIVER_ADDRESS="127.0.0.1"
ENV RECEIVER_PORT="8080"
ENV RECEIVER_URI="/upload"

WORKDIR /usr/src/app-sender

COPY Pipfile ./
COPY Pipfile.lock ./
RUN pip install --no-cache-dir pipenv
RUN pipenv install  --system --deploy --ignore-pipfile

COPY ./sender ./sender/


RUN mkdir -p /usr/src/app-sender/status-db \
    && mkdir -p /usr/src/app-sender/input && mkdir -p /run/secrets/  && touch /run/secrets/decryption_key


ENTRYPOINT ["python","./sender/__main__.py"]